[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

[[main]]
  identifier = "articles"
  name = "articles"
  url = "articles"
  weight = 2

[[main]]
identifier = "contact"
name = "contact"
url = "contact"
weight = 3